apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: default
  name: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: default
    spec:
      containers:
      - image: 547892456789123678912345789421/hello-world-kubernetes:latest
        name: hello-world-kubernetes
        resources: {}
status: {}
