apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: default
  name: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: default
    spec:
      containers:
      - image: 652549796343.dkr.ecr.eu-central-1.amazonaws.com/interview-app-backend:latest
        name: interview-app-backend
        resources: {}
status: {}
